title: alefvanoon # name of the site
author: alefvanoon # name of site's author
email: me@alefvanoon.xyz # email of site's author
url: https://alefvanoon.xyz # root address of the site
baseurl:  # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  alefvanoon Home.

permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

#theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please
remote_theme: riggraz/no-style-please

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page
  show_index_content_in_top: false # show content of index.md above menu

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
